/*
 * Apache License 2.0
 * Copyright (c) 2025–present Raman Marozau, Target Insight Function.
 * Contact: raman@worktif.com
 *
 * This file is part of the stdio bus protocol reference implementation:
 *   stdio_bus_kernel_workers (target: <target_stdio_bus_kernel_workers>).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Type definitions for the MCP-ACP protocol proxy.
 *
 * This module defines TypeScript interfaces for all state objects and message types
 * used by the proxy to convert between Model Context Protocol (MCP) and Agent Client
 * Protocol (ACP).
 */

/**
 * Configuration loaded from environment variables.
 *
 * @example
 * ```typescript
 * const config: ProxyConfig = {
 *   acpHost: process.env.ACP_HOST || '127.0.0.1',
 *   acpPort: parseInt(process.env.ACP_PORT || '9011', 10),
 *   agentId: process.env.AGENT_ID!
 * };
 * ```
 */
export interface ProxyConfig {
  /** ACP_HOST environment variable (default: 127.0.0.1) */
  acpHost: string;
  /** ACP_PORT environment variable (default: 9011) */
  acpPort: number;
  /** AGENT_ID environment variable (required) */
  agentId: string;
}

/**
 * Pending request tracking information.
 *
 * Tracks requests that have been sent but not yet received a response.
 * Used for correlating responses with their original requests and handling
 * queued requests (e.g., session/new followed by session/prompt).
 */
export interface PendingRequest {
  /** Original MCP or ACP method name */
  method: string;
  /** Original request parameters */
  params?: unknown;
  /** For queued requests: original request ID (session/new -> session/prompt) */
  originalId?: string | number;
  /** For queued prompts: the prompt text to send after session creation */
  promptText?: string;
}

/**
 * Session state maintained by the proxy.
 *
 * Manages session identifiers, pending requests, and accumulated text for
 * streaming responses.
 *
 * @example
 * ```typescript
 * const state: SessionState = {
 *   proxySessionId: 'proxy-1234567890',
 *   acpSessionId: 'session-abc123',
 *   pendingRequests: new Map(),
 *   accumulatedText: new Map()
 * };
 * ```
 */
export interface SessionState {
  /** Session ID for stdio Bus routing (generated by proxy) */
  proxySessionId: string | null;
  /** Session ID from ACP agent (received from session/new response) */
  acpSessionId: string | null;
  /** Map of request ID to pending request information */
  pendingRequests: Map<string | number, PendingRequest>;
  /** Map of request ID to accumulated streaming text */
  accumulatedText: Map<string | number, string>;
}

/**
 * MCP JSON-RPC request message.
 *
 * Represents a request from an MCP client (like IDE) to the proxy.
 * Uses JSON-RPC 2.0 format.
 */
export type MCPRequest = {
  /** JSON-RPC version (always '2.0') */
  jsonrpc: '2.0';
  /** Request identifier (string or number) */
  id: string | number;
  /** MCP method name (e.g., 'initialize', 'tools/list', 'tools/call') */
  method: string;
  /** Method-specific parameters */
  params?: unknown;
};

/**
 * MCP JSON-RPC response message.
 *
 * Represents a response from the proxy to an MCP client.
 * Contains either a result or an error, never both.
 */
export type MCPResponse = {
  /** JSON-RPC version (always '2.0') */
  jsonrpc: '2.0';
  /** Request identifier matching the original request */
  id: string | number;
  /** Success result (present if no error) */
  result?: unknown;
  /** Error information (present if request failed) */
  error?: {
    /** JSON-RPC error code */
    code: number;
    /** Human-readable error message */
    message: string;
  };
};

/**
 * ACP JSON-RPC request message.
 *
 * Represents a request from the proxy to an ACP agent via stdio Bus.
 * Extends JSON-RPC 2.0 with ACP-specific fields.
 */
export type ACPRequest = {
  /** JSON-RPC version (always '2.0') */
  jsonrpc: '2.0';
  /** Request identifier (string or number) */
  id: string | number;
  /** ACP method name (e.g., 'initialize', 'session/new', 'session/prompt') */
  method: string;
  /** Target agent identifier */
  agentId: string;
  /** Session identifier for stdio Bus routing */
  sessionId: string;
  /** Method-specific parameters */
  params?: unknown;
};

/**
 * ACP JSON-RPC response message.
 *
 * Represents a response from an ACP agent to the proxy.
 * Contains either a result or an error, never both.
 */
export type ACPResponse = {
  /** JSON-RPC version (always '2.0') */
  jsonrpc: '2.0';
  /** Request identifier matching the original request */
  id: string | number;
  /** Success result (present if no error) */
  result?: unknown;
  /** Error information (present if request failed) */
  error?: {
    /** JSON-RPC error code */
    code: number;
    /** Human-readable error message */
    message: string;
  };
};

/**
 * ACP JSON-RPC notification message.
 *
 * Represents a notification from an ACP agent to the proxy.
 * Notifications do not have an id field and do not expect a response.
 * Used for streaming updates like agent_message_chunk.
 */
export type ACPNotification = {
  /** JSON-RPC version (always '2.0') */
  jsonrpc: '2.0';
  /** Notification method name (e.g., 'session/update') */
  method: string;
  /** Notification-specific parameters */
  params?: unknown;
};
